image_root_dirs:
  - '/Volumes/Untitled/DCIM'
  - '/Users/{username}/Pictures/source'
  - '/Users/{username}/Pictures/export'
  - '/Users/{username}/Pictures/Lightroom CC Saved Photos'

  

image_extensions:
  - 'ARW'
  - 'JPG'

movie_root_dirs:
  - '/Users/{username}/Movies'
  - '/Volumes/Untitles/PRIVATE'

movie_extensions:
  - 'MOV'
  - 'MP4'

continuous_shoot_threshold_sec: 1

pixmap_cache_size: 1048576

icon_size: 32

folder_icon: 'icons/GenericFolderIcon.icns'
continuous_shoot_icon: 'icons/continuous-shooting-icon.png'

image_save_folder: '/Users/{username}/Pictures/source'
movie_save_folder: '/Users/{username}/Movies/source'
